[Settings]
; =========================
; 全局功能开关 / Global Switches
; =========================

# 单个频道接口数量 | Number of interfaces per channel
urls_limit = 5


; =========================
; 定时执行设置 / Scheduled Execution Settings
; =========================



; =========================
; 结果输出 & 服务配置 / Output & Service
; =========================

# 模板文件路径；默认值: config/demo.txt | Template file path; Default value: config/demo.txt
source_file = config/user_demo.txt
# 生成结果文件路径；默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/iptv.txt
# CDN 代理加速地址，用于订阅源、频道图标等资源的加速访问 | CDN proxy acceleration address, used for accelerated access to subscription sources, channel icons and other resources
cdn_url = https://gh-proxy.com/


; =========================
; 数据源总开关 / Source Global Switches
; =========================


; =========================
; 数据源工作模式 / Source Working Modes
; =========================


; =========================
; 过滤 & 测速设置 / Filtering & Speed Test
; =========================



# 接口最小分辨率，需要开启 open_filter_resolution 才能生效 | Minimum resolution of the interface, need to enable open_filter_resolution to take effect
min_resolution = 1920x1080
# 接口最大分辨率，需要开启 open_filter_resolution 才能生效 | Maximum resolution of the interface, need to enable open_filter_resolution to take effect
max_resolution = 1920x1080
# 接口最小速率（单位 M/s），需要开启 open_filter_speed 才能生效 | Minimum rate of the interface (unit M/s), need to enable open_filter_speed to take effect
min_speed = 2



; =========================
; 网络协议 & 地域偏好 / Network & Region Preferences
; =========================



; =========================
; 结果排序偏好 / Result Ordering Preference
; =========================



; =========================
; 本地源 / Local Source
; =========================

# 结果中偏好的本地源接口数量 | Preferred number of local source interfaces in the result
local_num = 10


; =========================
; 订阅源 / Subscription Source
; =========================

# 结果中偏好的订阅源接口数量 | Preferred number of subscription source interfaces in the result
subscribe_num = 10


; =========================
; 频道台标 / Channel Logo
; =========================

# 频道台标库地址 | Channel logo library address
logo_url = https://raw.githubusercontent.com/fanmingming/live/main/tv/
# 频道台标文件类型 | Channel logo file type
logo_type = png


; =========================
; RTMP 推流 / RTMP Push
; =========================
